apiVersion: v1
kind: ConfigMap
metadata:
  name: e2e-test2-config
  namespace: default
data:
  APP_ENV: "production"
  SERVICE_NAME: "e2e-test2"
  REDIS_URL: "redis://:$REDIS_PASSWORD@e2e-test2-redis-master.e2e-test2.svc.cluster.local:6379/0"
