apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: e2e-test2
  namespace: default
spec:
  components:
        
          - name: e2e-test2
            type: webservice
            properties:
              name: e2e-test2
              image: healthidpuaeacr.azurecr.io/e2e-test2:latest
              language: python
              framework: fastapi
              port: 8080
              healthPath: /health
              cache: redis
              appContainer: e2e-test2
              exposeApi: true
